Layout/LineLength:
    Max: 80

Metrics/AbcSize:
    Enabled: false

Metrics/PerceivedComplexity:
    Enabled: false

Metrics/ClassLength:
    Max: 1000

Metrics/ModuleLength:
    Max: 1000

Metrics/BlockLength:
    Max: 300

Metrics/CyclomaticComplexity:
    Enabled: false

Metrics/MethodLength:
    Max: 100

Style/FrozenStringLiteralComment:
    Enabled: false

Style/AccessorGrouping:
    Enabled: false

AllCops:
    TargetRubyVersion: 2.7
    Exclude:
        - 'Gemfile'
        - 'tildeconfig.gemspec'
        - 'Rakefile'
        - 'vendor/**/*'
        - 'bin/*'

# Other settings

Layout/EmptyLinesAroundAttributeAccessor:
    Enabled: true

Layout/SpaceAroundMethodCallOperator:
    Enabled: true

Lint/BinaryOperatorWithIdenticalOperands:
    Enabled: true

Lint/DeprecatedOpenSSLConstant:
    Enabled: true

Lint/DuplicateElsifCondition:
    Enabled: true

Lint/DuplicateRescueException:
    Enabled: true

Lint/EmptyConditionalBody:
    Enabled: true

Lint/FloatComparison:
    Enabled: true

Lint/MissingSuper:
    Enabled: true

Lint/MixedRegexpCaptureTypes:
    Enabled: true

Lint/OutOfRangeRegexpRef:
    Enabled: true

Lint/RaiseException:
    Enabled: true

Lint/SelfAssignment:
    Enabled: true

Lint/StructNewOverride:
    Enabled: true

Lint/TopLevelReturnWithArgument:
    Enabled: true

Lint/UnreachableLoop:
    Enabled: true

Style/ArrayCoercion:
    Enabled: true

Style/BisectedAttrAccessor:
    Enabled: true

Style/CaseLikeIf:
    Enabled: true

Style/ExplicitBlockArgument:
    Enabled: true

Style/ExponentialNotation:
    Enabled: true

Style/GlobalStdStream:
    Enabled: true

Style/HashAsLastArrayItem:
    Enabled: true

Style/HashEachMethods:
    Enabled: true

Style/HashLikeCase:
    Enabled: true

Style/HashTransformKeys:
    Enabled: true

Style/HashTransformValues:
    Enabled: true

Style/OptionalBooleanParameter:
    Enabled: true

Style/RedundantAssignment:
    Enabled: true

Style/RedundantFetchBlock:
    Enabled: true

Style/RedundantFileExtensionInRequire:
    Enabled: true

Style/RedundantRegexpCharacterClass:
    Enabled: true

Style/RedundantRegexpEscape:
    Enabled: true

Style/SingleArgumentDig:
    Enabled: true

Style/SlicingWithRange:
    Enabled: true

Style/StringConcatenation:
    Enabled: true
